// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/user/authenticator_anonymous.proto

package userpb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SetUserNameRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetUserNameRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetUserNameRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetUserNameRequestMultiError, or nil if none found.
func (m *SetUserNameRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SetUserNameRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetBizId()) < 1 {
		err := SetUserNameRequestValidationError{
			field:  "BizId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetUserName()) < 1 {
		err := SetUserNameRequestValidationError{
			field:  "UserName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SetUserNameRequestMultiError(errors)
	}

	return nil
}

// SetUserNameRequestMultiError is an error wrapping multiple validation errors
// returned by SetUserNameRequest.ValidateAll() if the designated constraints
// aren't met.
type SetUserNameRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetUserNameRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetUserNameRequestMultiError) AllErrors() []error { return m }

// SetUserNameRequestValidationError is the validation error returned by
// SetUserNameRequest.Validate if the designated constraints aren't met.
type SetUserNameRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetUserNameRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetUserNameRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetUserNameRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetUserNameRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetUserNameRequestValidationError) ErrorName() string {
	return "SetUserNameRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SetUserNameRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetUserNameRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetUserNameRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetUserNameRequestValidationError{}

// Validate checks the field values on SetUserNameResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetUserNameResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetUserNameResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetUserNameResponseMultiError, or nil if none found.
func (m *SetUserNameResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SetUserNameResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetStatus()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SetUserNameResponseValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SetUserNameResponseValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStatus()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SetUserNameResponseValidationError{
				field:  "Status",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SetUserNameResponseMultiError(errors)
	}

	return nil
}

// SetUserNameResponseMultiError is an error wrapping multiple validation
// errors returned by SetUserNameResponse.ValidateAll() if the designated
// constraints aren't met.
type SetUserNameResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetUserNameResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetUserNameResponseMultiError) AllErrors() []error { return m }

// SetUserNameResponseValidationError is the validation error returned by
// SetUserNameResponse.Validate if the designated constraints aren't met.
type SetUserNameResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetUserNameResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetUserNameResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetUserNameResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetUserNameResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetUserNameResponseValidationError) ErrorName() string {
	return "SetUserNameResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SetUserNameResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetUserNameResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetUserNameResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetUserNameResponseValidationError{}
